name: Markdown lint

on:
  pull_request:
    branches: [main]

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .github/markdownlint-rules
          dot: false
          ignore_files: LICENSE.md
